//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meetup.WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FIN_iRMS_Dev_ST_6JulyEntities : DbContext
    {
        public FIN_iRMS_Dev_ST_6JulyEntities()
            : base("name=FIN_iRMS_Dev_ST_6JulyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HWL_Categories> HWL_Categories { get; set; }
        public virtual DbSet<HWL_UserCategories> HWL_UserCategories { get; set; }
        public virtual DbSet<HWL_Users> HWL_Users { get; set; }
    }
}
